### ISSUE TITLE
point cloud -> grid also possible?

### ISSUE THREAD

**Issue by tomrobin-teschner** [pointwise/GridToSource#1]
Just wondering, is the reverse also possible? I.e. from a set of points, can that be injected into pointwise to generate a triangular surface mesh?

**Comment by pabakertx** [comment]
Tessellation of a point cloud is a long-standing feature request in Pointwise. There are currently no plans to implement this within the next year or so, but it is an active request.  Tessellation of point cloud to surface mesh can be done in a variety of ways, with no one method producing ideal results in all cases. MeshLab has some basic capabilities to do this, which can be exported to STL or OBJ format, and these can be read by Pointwise.
